import AlbumAction from "@/feature/details/components/action";
import { DataTable } from "@/feature/details/components/data-table";
import AlbumHeader from "@/feature/details/components/header";

const album = {
  id: 1,
  name: "Chilling?",
  cover_url: "https://placehold.co/400",
  authorName: "Truc Pham????",
  authorID: 1,
  dateAdded: "2021-10-01",
  tracks: [
    {
      id: 1,
      title: "My Heart Will Go On",
      cover_url: "https://placehold.co/400",
      artistName: "Céline Dion",
      artistID: 1,
      albumName: null,
      albumID: 1,
      dateAdded: "11/4/2022",
      duration: "3:21",
    },
    {
      id: 2,
      title: "Shape of You",
      cover_url: "https://placehold.co/400",
      artistName: "Ed Sheeran",
      artistID: 2,
      albumName: "Divide",
      albumID: 2,
      dateAdded: "12/10/2022",
      duration: "4:24",
    },
    {
      id: 3,
      title: "Blinding Lights",
      cover_url: "https://placehold.co/400",
      artistName: "The Weeknd",
      artistID: 3,
      albumName: "After Hours",
      albumID: 3,
      dateAdded: "1/15/2023",
      duration: "3:20",
    },
    {
      id: 4,
      title: "Rolling in the Deep",
      cover_url: "https://placehold.co/400",
      artistName: "Adele",
      artistID: 4,
      albumName: "21",
      albumID: 4,
      dateAdded: "2/5/2023",
      duration: "3:48",
    },
    {
      id: 5,
      title: "Uptown Funk",
      artistName: "Mark Ronson ft. Bruno Mars",
      cover_url: "https://placehold.co/400",
      artistID: 5,
      albumName: "Uptown Special",
      albumID: 5,
      dateAdded: "3/12/2023",
      duration: "4:30",
    },
    {
      id: 6,
      title: "Bohemian Rhapsody",
      cover_url: "https://placehold.co/400",
      artistName: "Queen",
      artistID: 6,
      albumName: "A Night at the Opera",
      albumID: 6,
      dateAdded: "4/2/2023",
      duration: "5:55",
    },
    {
      id: 7,
      title: "Hotel California",
      cover_url: "https://placehold.co/400",
      artistName: "Eagles",
      artistID: 7,
      albumName: "Hotel California",
      albumID: 7,
      dateAdded: "5/8/2023",
      duration: "6:30",
    },
    {
      id: 8,
      title: "Imagine",
      cover_url: "https://placehold.co/400",
      artistName: "John Lennon",
      artistID: 8,
      albumName: "Imagine",
      albumID: 8,
      dateAdded: "6/14/2023",
      duration: "3:03",
    },
    {
      id: 9,
      title: "Billie Jean",
      cover_url: "https://placehold.co/400",
      artistName: "Michael Jackson",
      artistID: 9,
      albumName: "Thriller",
      albumID: 9,
      dateAdded: "7/20/2023",
      duration: "4:54",
    },
    {
      id: 10,
      title: "Smells Like Teen Spirit",
      cover_url: "https://placehold.co/400",
      artistName: "Nirvana",
      artistID: 10,
      albumName: "Nevermind",
      albumID: 10,
      dateAdded: "8/1/2023",
      duration: "5:01",
    },
    {
      id: 11,
      title: "Wonderwall",
      cover_url: "https://placehold.co/400",
      artistName: "Oasis",
      artistID: 11,
      albumName: "(What's the Story) Morning Glory?",
      albumID: 11,
      dateAdded: "8/15/2023",
      duration: "4:18",
    },
    {
      id: 12,
      title: "Hey Jude",
      cover_url: "https://placehold.co/400",
      artistName: "The Beatles",
      artistID: 12,
      albumName: "Hey Jude",
      albumID: 12,
      dateAdded: "9/5/2023",
      duration: "7:11",
    },
    {
      id: 13,
      title: "Lose Yourself",
      cover_url: "https://placehold.co/400",
      artistName: "Eminem",
      artistID: 13,
      albumName: "8 Mile",
      albumID: 13,
      dateAdded: "10/2/2023",
      duration: "5:26",
    },
    {
      id: 14,
      title: "Sweet Child o' Mine",
      cover_url: "https://placehold.co/400",
      artistName: "Guns N' Roses",
      artistID: 14,
      albumName: "Appetite for Destruction",
      albumID: 14,
      dateAdded: "10/20/2023",
      duration: "5:56",
    },
    {
      id: 15,
      title: "Rolling in the Deep (Live)",
      cover_url: "https://placehold.co/400",
      artistName: "Adele",
      artistID: 4,
      albumName: "Live at the Royal Albert Hall",
      albumID: 15,
      dateAdded: "11/3/2023",
      duration: "4:05",
    },
    {
      id: 16,
      title: "Stairway to Heaven",
      cover_url: "https://placehold.co/400",
      artistName: "Led Zeppelin",
      artistID: 16,
      albumName: "Led Zeppelin IV",
      albumID: 16,
      dateAdded: "11/15/2023",
      duration: "8:02",
    },
    {
      id: 17,
      title: "Poker Face",
      cover_url: "https://placehold.co/400",
      artistName: "Lady Gaga",
      artistID: 17,
      albumName: "The Fame",
      albumID: 17,
      dateAdded: "12/1/2023",
      duration: "3:57",
    },
    {
      id: 18,
      title: "I Will Survive",
      cover_url: "https://placehold.co/400",
      artistName: "Gloria Gaynor",
      artistID: 18,
      albumName: "Love Tracks",
      albumID: 18,
      dateAdded: "12/12/2023",
      duration: "3:15",
    },
    {
      id: 19,
      title: "Thinking Out Loud",
      cover_url: "https://placehold.co/400",
      artistName: "Ed Sheeran",
      artistID: 2,
      albumName: "X",
      albumID: 19,
      dateAdded: "1/10/2024",
      duration: "4:41",
    },
    {
      id: 20,
      title: "Bad Guy",
      cover_url: "https://placehold.co/400",
      artistName: "Billie Eilish",
      artistID: 20,
      albumName: "When We All Fall Asleep, Where Do We Go?",
      albumID: 20,
      dateAdded: "1/25/2024",
      duration: "3:14",
    },
  ],
};

export default function AlbumPage() {
  return (
    <div className="min-h-full">
      <AlbumHeader
        cover_url="https://placehold.co/400"
        author_type="artist"
        author_id={1}
        author_name="Truc"
        title="This is album"
        type="Album"
      />
      <div className="px-4">
        <AlbumAction />
        <DataTable data={album.tracks} />
      </div>
    </div>
  );
}
