# Generated by Django 5.1.7 on 2025-03-23 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        ('user', '0002_userfollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('collection_type', models.CharField(choices=[('featured', 'Featured'), ('trending', 'Trending'), ('new_releases', 'New Releases'), ('genre_based', 'Genre Based'), ('mood_based', 'Mood Based'), ('seasonal', 'Seasonal')], max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collection_covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='collections', to='music.genre')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.collection')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('collection', 'song')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='songs',
            field=models.ManyToManyField(related_name='collections', through='playlist.CollectionSong', to='music.song'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='playlist_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlists', through='playlist.PlaylistSong', to='music.song'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['collection_type'], name='playlist_co_collect_4604c9_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['is_active'], name='playlist_co_is_acti_6769a1_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['slug'], name='playlist_co_slug_1743a7_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistsong',
            index=models.Index(fields=['playlist', 'position'], name='playlist_pl_playlis_e25ba0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistsong',
            unique_together={('playlist', 'song')},
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['name'], name='playlist_pl_name_087dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['created_at'], name='playlist_pl_created_ca699c_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['is_public'], name='playlist_pl_is_publ_db1a27_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['slug'], name='playlist_pl_slug_0a4ada_idx'),
        ),
    ]
