# Generated by Django 5.1.6 on 2025-04-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_alter_collection_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collection',
            name='playlist_co_slug_1743a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='playlist',
            name='playlist_pl_slug_0a4ada_idx',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='slug',
        ),
    ]
