# Generated by Django 5.1.7 on 2025-03-23 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        ('user', '0002_userfollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='user.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='purchase_pu_user_id_bea05b_idx'), models.Index(fields=['purchase_date'], name='purchase_pu_purchas_e4d3f2_idx'), models.Index(fields=['status'], name='purchase_pu_status_c9adfd_idx')],
                'unique_together': {('user', 'song')},
            },
        ),
    ]
