# Generated by Django 5.1.6 on 2025-03-30 10:59

import cloudinary_storage.storage
import django.core.validators
import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_song_audio_file_alter_song_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(resource_type='raw'), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'flac'])]),
        ),
        migrations.AlterField(
            model_name='song',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(resource_type='video'), upload_to='', validators=[music.models.custom_validate_video]),
        ),
    ]
