# Generated by Django 5.1.7 on 2025-04-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_audio_file_alter_song_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='composers',
            field=models.ManyToManyField(related_name='composed_songs', to='music.artist'),
        ),
    ]
