# Generated by Django 5.1.7 on 2025-04-09 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_composers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='composers',
        ),
        migrations.RemoveField(
            model_name='song',
            name='featuring_artists',
        ),
        migrations.CreateModel(
            name='SongArtistRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'Ca sĩ chính'), ('feature', 'Khách mời'), ('composer', 'Nhạc sĩ')], max_length=20)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_roles', to='music.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_roles', to='music.song')),
            ],
            options={
                'unique_together': {('song', 'artist', 'role')},
            },
        ),
    ]
