# Generated by Django 5.1.7 on 2025-04-09 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_remove_song_artist_remove_song_composers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='composers',
            field=models.ManyToManyField(related_name='composed_songs', to='music.artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='featuring_artists',
            field=models.ManyToManyField(blank=True, related_name='featured_in', to='music.artist'),
        ),
        migrations.DeleteModel(
            name='SongArtistRole',
        ),
    ]
