# Generated by Django 5.1.7 on 2025-04-09 22:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_song_artist_song_composers_song_featuring_artists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='album_covers'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='artist_images'),
        ),
    ]
