# Generated by Django 5.1.7 on 2025-04-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_userlibrary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLibrary',
        ),
    ]
