# Generated by Django 5.1.6 on 2025-04-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_delete_userlibrary'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='song',
            name='music_song_slug_f34e4d_idx',
        ),
        migrations.RemoveField(
            model_name='song',
            name='slug',
        ),
    ]
